### ISSUE TITLE
Optional packages with build-depends

### ISSUE THREAD

**Issue by szlin** [SleuthKid/hyperscan#2]
The packages  doxygen and libpcap-dev are optional in hyperscan, maybe tthese packages should be added into debian/control

**Comment by SleuthKid** [comment]
_dyxygen_, _sphinx_ and _libpcap-dev_ would be optional dependencies if we decide to also build a _libhyperscan-doc_ package.

**Comment by szlin** [comment]
You are right, which kind of binary package should be built (*-doc, *-dev, *dbg, etc...) with hyperscan ?

Frankly, I spent lots of time to split for these binary package, and still struggle on it so far...Perhaps we can choose some of them to build first version of hyperscan in Debian.

**Comment by SleuthKid** [comment]
The current proposal builds two packages -> _libhyperscan4.2_ and _libhyperscan-dev_
Those two should be sufficient for everyday use in the beginning. If there are active users that would actually benefit from having an additional libhyperscan-doc package we could also include this.

**Comment by szlin** [comment]
I have 2 following questions.

- The naming *libhyperscan4.2* needs to be modified in each release version (e.g., *libhyperscan4.3* when version 4.3 is released, how about using "libhyperscan" ?

- The upstream disable static library compilation option in default, but I think we should have both static and dynamic libraries in  **libhyperscan-dev**

**Comment by SleuthKid** [comment]
Okay I think I can answer that:

The package naming convention encourages using MAJOR.MINOR versions attached to libraries to allow users to install different versions of a library which might be needed by depending software

We already build shared and static versions with the current config (see debian/rules):
```
override_dh_auto_configure:
	dh_auto_configure -- -DBUILD_STATIC_AND_SHARED=1
```

**Comment by szlin** [comment]
Thanks for your patient explanation.

**Comment by szlin** [comment]
According to  https://wiki.debian.org/DebugPackage,  it will generate debug symbol packages (as <package>-dbgsym) for you with no additional changes to your source package.

It generates "libhyperscan4.2-dbgsym_4.2.0-2_i386.deb" afterward.
