### ISSUE TITLE
Packaging hyperscan with Git/GitDpm

### ISSUE THREAD

**Issue by szlin** [SleuthKid/hyperscan#3]
I suggest that we can pack hyperscan by using git-dpm to handle debian patch.

https://wiki.debian.org/PackagingWithGit/GitDpm

**Comment by hillu** [comment]
I have so far worked with `git-buildpackage`. Do you see a specific advantage in using `git-dpm`?

**Comment by szlin** [comment]
These two commands *are not conflict* with each other, git-dpm is one of git-buildpackage family commands. 

All modification from upstream source could convert to patch/* automatically.

git-dpm pros [1]:
- use git to manage patches
- use git to allow an otherwise unchanged packaging workflow
- do as much as possible with git as naively as possible 

Debian Python team has chosen git-dpm instead of gbp on git workflows [4].
I also use git-dpm to mange my package so far [2].

Of course, all mechanism is OK for me. I totally respect your decision :)

ref: 
[1] http://git-dpm.alioth.debian.org/git-dpm-debconf13.pdf
[2] https://anonscm.debian.org/git/collab-maint/googler.git
[3] https://wiki.debian.org/PackagingWithGit/GitDpm
[4] https://wiki.debian.org/Python/GitPackaging

**Comment by SleuthKid** [comment]
We will hopefully have a colab git repo for hyperscan at alioth this week. We should then use the git-buildpackage toolchain of course :)
