### ISSUE TITLE
Who can upload?

### ISSUE THREAD

**Issue by hillu** [SleuthKid/hyperscan#5]
I'm a DD, so I can do the initial upload and otherwise sponsor the package. We'lll have to see about making Robert at least a DM really soon now... :-)

@szlin what about you?

**Comment by szlin** [comment]
I'm a DM, and therefore I can maintain the package after uploading by sponsor. 
But I suggest that we need to classify some issues before uploading package to Alioth/Git or Debian archive.

**Comment by hillu** [comment]
Sure, it's not done yet.

**Comment by SleuthKid** [comment]
We sucessfully put hyperscan into unstable and pushed the first patched build for the reproducible team: https://tracker.debian.org/pkg/hyperscan

We will hopefully have collabrative git repo @alioth this week.
