### ISSUE TITLE
Debconf integration with preinst

### ISSUE THREAD

**Issue by hillu** [SleuthKid/hyperscan#7]
The preinst check for SSSE3 that I added in 19ba82af5ee2522ade04d37b5f00cf737c0db010 needs to interact with the user via the Debconf -- preferably with an "Abort installation? Y/N" question. I'll try to get that done by Monday.

**Comment by hillu** [comment]
Done, I think. a1f87257cb02e8f42f6ec745fa6916f159e5b5a5

**Comment by SleuthKid** [comment]
Can confirm this switch works. Closed for now although there might be some corner cases left
